### ISSUE TITLE
Port to Gnome 45

### ISSUE THREAD

**Issue by muerwre** [artisticat1/gnome-next-up#15]
Hello! Gnome 45 introduces new ES-like imports. I tried to port it myself, but `ExtensionUtils` also changed.

Here's the migration guide: https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by coignard** [comment]
Hey @muerwre, I have added support for GNOME 45 in my [fork](https://github.com/coignard/caldav-status-bar)

**Comment by muerwre** [comment]
Closed as duplicate of #17
