### ISSUE TITLE
Update to Gnome 46

### ISSUE THREAD

**Issue by Amereyeu** [artisticat1/gnome-next-up#17]
could you update the plugin so it works in gnome 46? thanks

**Comment by muerwre** [comment]
@Amereyeu @artisticat1 I've made PR for migrating: https://github.com/artisticat1/gnome-next-up/pull/18, tested it on my Gnome 46 machine.

As temporary solution for get it working until (and if) that PR will be merged, you can do following:

Remove extension and execute following commands:

```shell
rm -r ~/.local/share/gnome-shell/extensions/next-up@artisticat1.github.com
git clone -b v45 https://github.com/muerwre/gnome-next-up.git
ln -s gnome-next-up ~/.local/share/gnome-shell/extensions/next-up@artisticat1.github.com
```

Then restart shell and enable extension
